### ISSUE TITLE
GCR Authentication Unable to parse json key

### ISSUE THREAD

**Issue by kunal-relan** [circleci/circleci-docs#2436] opened 2018-06-22 11:18 UTC
I have tried using gcr using json_key method and it's always giving Unable to parse json key error, not sure if it's a bug or an issue at my end, so also pasting our config file.

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: us.gcr.io/project-id/image-id
        auth:
            username: _json_key
            password: $GCLOUD_SERVICE_KEY
    environment:
        GCLOUD_SERVICE_KEY: {JSON Content here}

**Comment by smart-alek** [comment] 2018-06-22 17:19
Hey @kunal-relan, thanks for filing this issue!

In the [original issue](https://github.com/circleci/circleci-docs/pull/2195/files), the problem was caused by encoding the JSON key file in base 64 format. Are you encoding the JSON key file at all? Or is this failing even when you create a project environment variable called `GCLOUD_SERVICE_KEY`?

**Comment by smart-alek** [comment] 2018-06-26 17:50
Hey @kunal-relan, since I didn't get any additional details, I'm going to close this issue for now. If you're still having trouble, check out our [Discuss forum](https://discuss.circleci.com/), or head over to our [Support Center](https://support.circleci.com/hc/en-us).

**Closed by smart-alek** 2018-06-26 17:50 UTC
Labels: Support
