### ISSUE TITLE
$BASH_ENV does not seem to be sourced

### ISSUE THREAD

**Issue by zinob** [circleci/circleci-docs#1650] opened 2017-10-10 09:13 UTC
This issue is about <https://circleci.com/docs/2.0/env-vars/> (source file: <https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/env-vars.md>)

According to the documentation  i should echo commands into $BASH_ENV in order to interpolate variables so i did: 
` - run: echo 'echo Ad nocendum potentes sumus ;export ZAPP_NAME=$CIRCLE_PROJECT_REPONAME HELM_NAME=$(echo ${ZAPP_NAME}|tr "_" "-")' >> $BASH_ENV `
Which should set some env-vars and also echo a threat in Latin every-time an line is executed this sadly does not hapen.

**Comment by FlashFlash1** [comment] 2017-10-10 09:26
William Flash

Get Outlook.for.Android/William Flash Jr

I have been with GitHub for very long time main idea main idea main idea main idea on main idea on main idea on main idea on GitHub main idea on GitHub main idea on GitHub main idea on GitHub is main idea on GitHub is when main idea on GitHub is when maybe there is maybe there is a maybe there is a job maybe there is a job for maybe there is a job for maybe there is a job for maybe there is a job for maybe there is a job for get maybe there is a job for get maybe there is a job for get maybe there is a job for get maybe there is a job for get Hub to do maybe there is a job for get Hub to do right here for some for some reason for some reason for some reason for some reason for some reason everything for some reason everything for some reason everything isn't for some reason everything isn't for some reason everything isn't working for some reason everything isn't working properly for some reason everything isn't working properly I don't I don't have I don't have I don't have the time I don't have the time to I don't have the time to do I don't have the time to do everything everything myself everything myself etiquette Hub has etiquette Hub has etiquette Hub has etiquette Hub has etiquette Hub has etiquette Hub has a technician there etiquette Hub has a technician there etiquette Hub has a technician there to etiquette Hub has a technician there to etiquette Hub has a technician there to please etiquette Hub has a technician there to please etiquette Hub has a technician there to please fix etiquette Hub has a technician there to please fix this etiquette Hub has a technician there to please fix this etiquette Hub has a technician there to please fix this phone etiquette Hub has a technician there to please fix this phone etiquette Hub has a technician there to please fix this phone etiquette Hub has a technician there to please fix this phone that etiquette Hub has a technician there to please fix this phone that would etiquette Hub has a technician there to please fix this phone that would be etiquette Hub has a technician there to please fix this phone that would be if GitHub has a technician there to please fix this phone that would be appreciated the the main job the main job the main job the main job the main job for getting up right the main job for getting up right now the main job for getting up right now the main job for getting up right now the main job for getting up right now was the main job for getting up right now was the main job for getting up right now was to the main job for getting up right now was to the main job for getting up right now was to take the main job for getting up right now was to take care the main job for getting up right now was to take care of the main job for getting up right now was to take care of the main job for getting up right now was to take care of finances the main job for getting up right now was to take care of finances what's get what's get what's get the what's get the finances what's get the finances so what's get the finances so I get I get I get I get the business I get the business up I get the business up and running proper I get the business up and running proper which is supposed to be which is supposed to be no which is supposed to be no problem which is supposed to be no problem and and and and and and circle and circle Bank and circle Bank I don't know I don't know what I don't know what the deal is there I don't know what the deal is there had account had account with them had account with them had account with them had account with them they had account with them they had account with them they had account with them they seem to had account with them they seem to lost money had account with them they seem to lost money at at at they at they having that would not be the story that was told to me that would not be the story that was told to Me that would not be the story that was told to me that would not be the story that was told to me three years that would not be the story that was told to me three years ago that would not be the story that was told to me three years ago that would not be the story that was told to me three years ago that would not be the story that was told to me three years ago or that would not be the story that was told to me three years ago or whatever that would not be the story that was told to me three years ago or whatever it was that would not be the story that was told to me three years ago or whatever it was nothing can be done nothing can be done right here nothing can be done right here I nothing can be done right here I would like for nothing can be done right here I would like for nothing can be done right here I would like for get nothing can be done right here I would like for get hug nothing can be done right here I would like for get hug to remove itself nothing can be done right here I would like for get hug to remove itself nothing can be done right here I would like for get hug to remove itself from the nothing can be done right here I would like for get hug to remove itself from the system and and and Order or and Order systems that that that belonged to that belonged to flash that belonged to flash William Flash Jr Jr William William flash 96 William flash 96 William flash 96 William flash 96 at William flash 96 at gmail.com William flash 96 at gmail.com flash social Med gmail com or or or if or if we're still working or if we're still working or if we're still working or if we're still working or if we're still working together like we were or if we're still working together like we were supposed or if we're still working together like we were supposed to or if we're still working together like we were supposed to help me get everything fixed alright God bless alright God bless
________________________________

**Comment by saveman71** [comment] 2017-10-23 22:04
Yep, I can confirm that this, unfortunately, does not seem to work on my end either.
Currently, I'm only trying on local with the following versions:
```
$ circleci version
circleci version: 0.0.4421-abcc223
Build Agent version: 0.0.4420-abcc223
built: 2017-10-23T13:23:35+0000
```

**Comment by dennybaa** [comment] 2018-01-22 13:56
Such an annoying odd thing. Until now doesn't work :-1: 
```
Build Agent version: 0.0.4654-b4e35bd
built: 2018-01-18T16:23:59+0000
```

**Comment by michelle-luna** [comment] 2018-02-20 21:51
Closing since there wasn't a response, if this update to the docs doesn't help, please file a new issue.

**Comment by ajhodges** [comment] 2018-03-16 15:48
@michelle-luna this is still unclear to me. Is BASH_ENV not `source`d automatically? If not, then what is the purpose of that file?

Similar to the other users above, I have this use case:
```
- run:
          name: Create version tag
          command: |
            echo 'export VERSION_TAG=build-$CIRCLE_BUILD_NUM-$(date +%F)' >> $BASH_ENV

- run:
          name: Push image to ECR
          command: |
            docker tag image-name image-name:$VERSION_TAG &&
            docker push image-name:$VERSION_TAG
```

So what do I have to do to make this work? Do I need to add a .bashrc with `source $BASH_ENV` inside it to my project?

**Comment by srgl** [comment] 2018-04-03 05:49
@ajhodges BASH_ENV is purely bash-thing. So for example if you use alpine based docker image, which has dash by default, it will not work. I believe @circleci team should make it clear in their docs.

**Comment by smart-alek** [comment] 2018-04-03 17:26
Hey @srgl and @ajhodges! Thanks for the feedback.

Not to completely change the topic, but have either of you tried the [updated workaround](https://circleci.com/docs/2.0/env-vars/#interpolating-environment-variables). It doesn't depend on `BASH_ENV` or need the `.bashrc`.

Let me know if you're still having issues!

**Comment by srgl** [comment] 2018-04-03 17:33
@smart-alek Does this example imply that exported variable value will be available in the next run step? Cause I believe this issue is all about passing run-time defined environment variables to following run steps.

**Comment by smart-alek** [comment] 2018-04-03 17:44
@srgl Aha, thanks for the clarification! I thought this was an issue purely related to env var interpolation rather than forwarding run-time env vars.

It's possible that I removed the answer you needed in one my more recent pushes, but I'm doing some digging on this and will get back to you soon.

**Comment by smart-alek** [comment] 2018-04-04 00:10
Hi folks!

While there's a PR in review, I wanted to clarify what's happening here:

1. If you've got an environment with bash, you can use the workaround that's been posted a few times in this thread — and which I've just added to the docs. Unfortunately, this one (as we've discovered) doesn't work with alpine-based images.

2. Each step runs in its own shell, so if you have commands that depend on runtime definition of an environment variable, your only option is to combine those commands into a single step. This is something that's actively being considered for development, so if you'd like that feature, put some pressure on our [ideas board](https://circleci.com/ideas/)! :)

Let me know if that answers everyone's questions!

**Closed** 2018-04-05 20:50 UTC
Labels: Clarification

**Comment by jack-sf** [comment] 2019-08-23 12:59
Could we at least update the docs, so that it explicitly points out that the `$BASH_ENV` workaround won't work on alpine-based images, and that we have to explicitly do `source $BASH_ENV` before each command that relies on it?

**Comment by eyal-solomon1** [comment] 2023-09-13 07:56
> Could we at least update the docs, so that it explicitly points out that the `$BASH_ENV` workaround won't work on alpine-based images, and that we have to explicitly do `source $BASH_ENV` before each command that relies on it?

4 years later .. had to waste time on why `$BASH_ENV` doesn't works
thanks !!
