### ISSUE TITLE
Clarify whether cache supports wildcard paths (_cci1/how-cache-works.md)

### ISSUE THREAD

**Issue by ianwremmel** [circleci/circleci-docs#241] opened 2016-07-15 21:23 UTC
It's unclear from these docs if the cache supports wildcard paths. Experimentation implies it does not.

It would be really great for monorepo node projects to be able to specify something like:

``` yml
cache:
  - node_modules
  - packages/*/node_modules
```

**Comment by smart-alek** [comment] 2017-03-14 22:09
@ianwremmel late to the party, but thanks for filing this!

We're closing issues for 1.0 doc edits in favor of fleshing out our [2.0 docs](https://circleci.com/docs/2.0/). Just didn't want you to leave you hanging or wondering what happened. :)

**Closed by smart-alek** 2017-03-14 22:09 UTC
Labels: Priority: Low, Status: Confirmed, Type: Edit

**Comment by Hypnosphi** [comment] 2018-02-18 18:15
The issue is still present in 2.0

It's very inconvenient to list all the packages explicitly under  `paths` key instead of just writing this:
```
- save_cache:
    key: core-dependencies-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - packages/*/node_modules
```
